# Generated by Django 4.1.1 on 2022-09-13 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gateway_check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان')),
                ('payment_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('tracking_code', models.IntegerField(unique=True, verbose_name='کد پیگیری')),
            ],
        ),
    ]
