# Generated by Django 4.0.5 on 2022-09-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
