# Generated by Django 4.0.5 on 2022-09-11 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productname', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قیمت')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='توضیحات')),
                ('image', models.ImageField(default='img.png', max_length=52428, upload_to='uploads/images/', verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='آدرس')),
                ('body', models.TextField(verbose_name='متن')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروز شده')),
                ('upload', models.FileField(max_length=524288, upload_to='uploads/files/', verbose_name='فایل')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس یا در انتظار تایید'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ManyToManyField(to='frontend.category', verbose_name='دسته بندی')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
