# Generated by Django 4.0.5 on 2022-09-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
