# Generated by Django 4.1.1 on 2022-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.AddField(
            model_name='cart',
            name='position',
            field=models.IntegerField(default=1, verbose_name='پوزیشن'),
        ),
    ]
