# Generated by Django 4.1.1 on 2022-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pids',
            field=models.ManyToManyField(blank=True, to='frontend.product', verbose_name='محصولات'),
        ),
    ]
